name: android
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/android.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'src/*'
      - 'src/layer/*'
      - 'src/layer/arm/**'
      - 'src/layer/riscv/**'
      - 'src/layer/x86/**'
      - 'src/layer/vulkan/**'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/android.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'src/*'
      - 'src/layer/*'
      - 'src/layer/arm/**'
      - 'src/layer/riscv/**'
      - 'src/layer/x86/**'
      - 'src/layer/vulkan/**'
concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NCNN_CMAKE_OPTIONS: |
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_PLATFORM=android-21 \
        -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
        -DCMAKE_INSTALL_PREFIX=install \
        -DCMAKE_BUILD_TYPE=Release \
        -DNCNN_VULKAN=ON \

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: armeabi-v7a
      run: |
        mkdir build-armeabi-v7a && cd build-armeabi-v7a
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON ..
        cmake --build . -j $(nproc)
    - name: Upload armeabi-v7a artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a-build-output
        path: build-armeabi-v7a/ # 或者指定更具体的路径，例如 build-armeabi-v7a/install/lib

    - name: arm64-v8a
      run: |
        mkdir build-arm64-v8a && cd build-arm64-v8a
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="arm64-v8a" ..
        cmake --build . -j $(nproc)
    - name: Upload arm64-v8a artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arm64-v8a-build-output
        path: build-arm64-v8a/

    - name: x86
      run: |
        mkdir build-x86 && cd build-x86
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="x86" ..
        cmake --build . -j $(nproc)
    - name: Upload x86 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x86-build-output
        path: build-x86/

    - name: x86_64
      run: |
        mkdir build-x86_64 && cd build-x86_64
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="x86_64" ..
        cmake --build . -j $(nproc)
    - name: Upload x86_64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-build-output
        path: build-x86_64/

    - name: riscv64
      run: |
        mkdir build-riscv64 && cd build-riscv64
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="riscv64" ..
        cmake --build . -j $(nproc)
    - name: Upload riscv64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: riscv64-build-output
        path: build-riscv64/

    - name: armeabi-v7a-shared
      run: |
        mkdir build-armeabi-v7a-shared && cd build-armeabi-v7a-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
    - name: Upload armeabi-v7a-shared artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a-shared-build-output
        path: build-armeabi-v7a-shared/

    - name: arm64-v8a-shared
      run: |
        mkdir build-arm64-v8a-shared && cd build-arm64-v8a-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="arm64-v8a" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
    - name: Upload arm64-v8a-shared artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arm64-v8a-shared-build-output
        path: build-arm64-v8a-shared/

    - name: x86-shared
      run: |
        mkdir build-x86-shared && cd build-x86-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="x86" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
    - name: Upload x86-shared artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x86-shared-build-output
        path: build-x86-shared/

    - name: x86_64-shared
      run: |
        mkdir build-x86_64-shared && cd build-x86_64-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="x86_64" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
    - name: Upload x86_64-shared artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-shared-build-output
        path: build-x86_64-shared/

    - name: riscv64-shared
      run: |
        mkdir build-riscv64-shared && cd build-riscv64-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="riscv64" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
    - name: Upload riscv64-shared artifacts
      uses: actions/upload-artifact@v4
      with:
        name: riscv64-shared-build-output
        path: build-riscv64-shared/


  ndk-r16b:
    runs-on: ubuntu-latest
    env:
      NCNN_CMAKE_OPTIONS: |
        -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/android-ndk-r16b/build/cmake/android.toolchain.cmake \
        -DANDROID_PLATFORM=android-21 \
        -DCMAKE_INSTALL_PREFIX=install \
        -DCMAKE_BUILD_TYPE=Release \
        -DNCNN_VULKAN=ON \

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: ndk-r16b
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        pushd /usr/lib/x86_64-linux-gnu/
        sudo ln -s libncurses.so.6 libncurses.so.5
        sudo ln -s libtinfo.so.6 libtinfo.so.5
        popd
        wget -q https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O $GITHUB_WORKSPACE/android-ndk-r16b-linux-x86_64.zip
        cd $GITHUB_WORKSPACE && unzip -q android-ndk-r16b-linux-x86_64.zip

    - name: armeabi-v7a
      run: |
        mkdir build-armeabi-v7a && cd build-armeabi-v7a
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON ..
        cmake --build . -j $(nproc)
    - name: Upload armeabi-v7a (r16b) artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a-r16b-build-output
        path: build-armeabi-v7a/

    - name: armeabi-v7a-no-neon
      run: |
        mkdir build-armeabi-v7a-no-neon && cd build-armeabi-v7a-no-neon
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=OFF ..
        cmake --build . -j $(nproc)
    - name: Upload armeabi-v7a-no-neon (r16b) artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a-no-neon-r16b-build-output
        path: build-armeabi-v7a-no-neon/

    - name: arm64-v8a
      run: |
        mkdir build-arm64-v8a && cd build-arm64-v8a
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="arm64-v8a" ..
        cmake --build . -j $(nproc)
    - name: Upload arm64-v8a (r16b) artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arm64-v8a-r16b-build-output
        path: build-arm64-v8a/

    - name: armeabi-v7a-shared
      run: |
        mkdir build-armeabi-v7a-shared && cd build-armeabi-v7a-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
    - name: Upload armeabi-v7a-shared (r16b) artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a-shared-r16b-build-output
        path: build-armeabi-v7a-shared/

    - name: armeabi-v7a-no-neon-shared
      run: |
        mkdir build-armeabi-v7a-no-neon-shared && cd build-armeabi-v7a-no-neon-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=OFF -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
    - name: Upload armeabi-v7a-no-neon-shared (r16b) artifacts
      uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a-no-neon-shared-r16b-build-output
        path: build-armeabi-v7a-no-neon-shared/

    - name: arm64-v8a-shared
      run: |
        mkdir build-arm64-v8a-shared && cd build-arm64-v8a-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="arm64-v8a" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
    - name: Upload arm64-v8a-shared (r16b) artifacts
      uses: actions/upload-artifact@v4
      with:
        name: arm64-v8a-shared-r16b-build-output
        path: build-arm64-v8a-shared/
