name: android
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/android.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'src/*'
      - 'src/layer/*'
      - 'src/layer/arm/**'
      - 'src/layer/riscv/**'
      - 'src/layer/x86/**'
      - 'src/layer/vulkan/**'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/android.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'src/*'
      - 'src/layer/*'
      - 'src/layer/arm/**'
      - 'src/layer/riscv/**'
      - 'src/layer/x86/**'
      - 'src/layer/vulkan/**'
concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NCNN_CMAKE_OPTIONS: |
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
        -DANDROID_PLATFORM=android-21 \
        -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON \
        -DCMAKE_INSTALL_PREFIX=install \
        -DCMAKE_BUILD_TYPE=Release \
        -DNCNN_VULKAN=ON \

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: armeabi-v7a - Static (Vulkan)
      run: |
        mkdir build-armeabi-v7a && cd build-armeabi-v7a
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload armeabi-v7a Static (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-armeabi-v7a-static-vulkan
        path: build-armeabi-v7a/install/

    - name: arm64-v8a - Static (Vulkan)
      run: |
        mkdir build-arm64-v8a && cd build-arm64-v8a
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="arm64-v8a" ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload arm64-v8a Static (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-arm64-v8a-static-vulkan
        path: build-arm64-v8a/install/

    - name: x86 - Static (Vulkan)
      run: |
        mkdir build-x86 && cd build-x86
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="x86" ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload x86 Static (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-x86-static-vulkan
        path: build-x86/install/

    - name: x86_64 - Static (Vulkan)
      run: |
        mkdir build-x86_64 && cd build-x86_64
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="x86_64" ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload x86_64 Static (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-x86_64-static-vulkan
        path: build-x86_64/install/

    - name: riscv64 - Static (Vulkan)
      run: |
        mkdir build-riscv64 && cd build-riscv64
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="riscv64" ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload riscv64 Static (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-riscv64-static-vulkan
        path: build-riscv64/install/

    - name: armeabi-v7a - Shared (Vulkan)
      run: |
        mkdir build-armeabi-v7a-shared && cd build-armeabi-v7a-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload armeabi-v7a Shared (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-armeabi-v7a-shared-vulkan
        path: build-armeabi-v7a-shared/install/

    - name: arm64-v8a - Shared (Vulkan)
      run: |
        mkdir build-arm64-v8a-shared && cd build-arm64-v8a-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="arm64-v8a" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload arm64-v8a Shared (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-arm64-v8a-shared-vulkan
        path: build-arm64-v8a-shared/install/

    - name: x86 - Shared (Vulkan)
      run: |
        mkdir build-x86-shared && cd build-x86-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="x86" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload x86 Shared (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-x86-shared-vulkan
        path: build-x86-shared/install/

    - name: x86_64 - Shared (Vulkan)
      run: |
        mkdir build-x86_64-shared && cd build-x86_64-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="x86_64" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload x86_64 Shared (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-x86_64-shared-vulkan
        path: build-x86_64-shared/install/

    - name: riscv64 - Shared (Vulkan)
      run: |
        mkdir build-riscv64-shared && cd build-riscv64-shared
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="riscv64" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload riscv64 Shared (Vulkan) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-riscv64-shared-vulkan
        path: build-riscv64-shared/install/

  ndk-r16b:
    runs-on: ubuntu-latest
    env:
      NCNN_CMAKE_OPTIONS: |
        -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/android-ndk-r16b/build/cmake/android.toolchain.cmake \
        -DANDROID_PLATFORM=android-21 \
        -DCMAKE_INSTALL_PREFIX=install \
        -DCMAKE_BUILD_TYPE=Release \
        -DNCNN_VULKAN=ON \

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: ndk-r16b - Setup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        pushd /usr/lib/x86_64-linux-gnu/
        sudo ln -s libncurses.so.6 libncurses.so.5
        sudo ln -s libtinfo.so.6 libtinfo.so.5
        popd
        wget -q https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O $GITHUB_WORKSPACE/android-ndk-r16b-linux-x86_64.zip
        cd $GITHUB_WORKSPACE && unzip -q android-ndk-r16b-linux-x86_64.zip

    - name: armeabi-v7a - Static (Vulkan, NDK r16b)
      run: |
        mkdir build-armeabi-v7a-r16b && cd build-armeabi-v7a-r16b
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload armeabi-v7a Static (Vulkan, NDK r16b) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-armeabi-v7a-static-vulkan-r16b
        path: build-armeabi-v7a-r16b/install/

    - name: armeabi-v7a-no-neon - Static (Vulkan, NDK r16b)
      run: |
        mkdir build-armeabi-v7a-no-neon-r16b && cd build-armeabi-v7a-no-neon-r16b
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=OFF ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload armeabi-v7a-no-neon Static (Vulkan, NDK r16b) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-armeabi-v7a-no-neon-static-vulkan-r16b
        path: build-armeabi-v7a-no-neon-r16b/install/

    - name: arm64-v8a - Static (Vulkan, NDK r16b)
      run: |
        mkdir build-arm64-v8a-r16b && cd build-arm64-v8a-r16b
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="arm64-v8a" ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload arm64-v8a Static (Vulkan, NDK r16b) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-arm64-v8a-static-vulkan-r16b
        path: build-arm64-v8a-r16b/install/

    - name: armeabi-v7a - Shared (Vulkan, NDK r16b)
      run: |
        mkdir build-armeabi-v7a-shared-r16b && cd build-armeabi-v7a-shared-r16b
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload armeabi-v7a Shared (Vulkan, NDK r16b) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-armeabi-v7a-shared-vulkan-r16b
        path: build-armeabi-v7a-shared-r16b/install/

    - name: armeabi-v7a-no-neon - Shared (Vulkan, NDK r16b)
      run: |
        mkdir build-armeabi-v7a-no-neon-shared-r16b && cd build-armeabi-v7a-no-neon-shared-r16b
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=OFF -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload armeabi-v7a-no-neon Shared (Vulkan, NDK r16b) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-armeabi-v7a-no-neon-shared-vulkan-r16b
        path: build-armeabi-v7a-no-neon-shared-r16b/install/

    - name: arm64-v8a - Shared (Vulkan, NDK r16b)
      run: |
        mkdir build-arm64-v8a-shared-r16b && cd build-arm64-v8a-shared-r16b
        cmake ${{ env.NCNN_CMAKE_OPTIONS }} -DANDROID_ABI="arm64-v8a" -DNCNN_SHARED_LIB=ON ..
        cmake --build . -j $(nproc)
        cmake --install .
    - name: Upload arm64-v8a Shared (Vulkan, NDK r16b) Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ncnn-android-arm64-v8a-shared-vulkan-r16b
        path: build-arm64-v8a-shared-r16b/install/
